# Generated by Django 6.0.3 on 2026-05-10 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dachas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
